# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

sudo: true
dist: trusty
cache: packages
warnings_are_errors: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

packages:
- libcurl4-openssl-dev
- libxml2-dev
- libgsl0-dev
